name: Tests

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: wget
      run: mkdir ci-bin/ && wget -O ci-bin/calcit_runner http://repo.calcit-lang.org/binaries/linux/calcit_runner
    - name: "permission"
      run: chmod +x ci-bin/calcit_runner

    - name: "prepare modules"
      run: >
        mkdir -p ~/.config/calcit/modules/ && cd ~/.config/calcit/modules/
        && git clone https://github.com/calcit-lang/lilac

    - name: "test"
      run: env=ci ./ci-bin/calcit_runner --once
