name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/calcit-lang/calcit/releases/download/0.8.9/cr'
        name: 'cr'
        version: '0.8.9'

    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/calcit-lang/calcit/releases/download/0.8.5/caps'
        name: 'caps'
        version: '0.8.5'

    - name: "test"
      run: caps --ci && env=ci cr -1
